- name: Check if mysqld_exporter is installed
  ansible.builtin.import_tasks: check_if_mysqld_exporter_installed.yml

- name: Setup and configure mysqld_exporter if not installed
  block:
    - name: Ensure mysqld_exporter package archive is ready(delegate_to dbbot server)
      ansible.builtin.import_tasks: ../../common_utils/tasks/ensure_local_tar_archive_ready.yml
      vars:
        local_tar_archive_label: "mysqld_exporter package {{ mysqld_exporter_package }}"
        local_tar_archive_path: "{{ mysql_packages_dir }}/{{ mysqld_exporter_package }}"
        local_tar_archive_auto_download: "{{ fcs_auto_download_packages | bool }}"
        local_tar_archive_url: "{{ mysqld_exporter_url }}"
        local_tar_archive_timeout: 60
        local_tar_archive_headers:
          User-Agent: "Wget/1.21.1"
        local_tar_archive_validate_certs: false
      when: mysqld_exporter_install_type == 'package'

    - name: Create user and make dir
      ansible.builtin.import_tasks: create_user_and_dir.yml

    - name: Setup mysqld_exporter by package
      ansible.builtin.import_tasks: setup_mysqld_exporter_by_package.yml
      when: mysqld_exporter_install_type == 'package'

    - name: Setup mysqld_exporter
      ansible.builtin.import_tasks: setup_mysqld_exporter.yml
      when: mysqld_exporter_install_type != 'package'

    - name: Config mysqld_exporter
      ansible.builtin.import_tasks: config_mysqld_exporter.yml

    - name: Manage mysqld_exporter service (create systemd service, enable and start)
      ansible.builtin.import_tasks: manage_service.yml
  when: not (mysqld_exporter_installed | default(false))

- name: Validate mysqld_exporter service is operational
  ansible.builtin.import_tasks: validate_service.yml
