{
 "title": "MySQL Router Overview",
 "tags": [
  "Percona",
  "MySQL_Router"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(mysqlrouter_up, environment)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(mysqlrouter_up{environment=~\"$environment\"}, region)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mysqlrouter_up{environment=~\"$environment\", region=~\"$region\"}, cluster)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values(mysqlrouter_up{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\"}, replication_set)"
    }
   },
   {
    "name": "topology",
    "label": "Topology",
    "query": {
     "query": "label_values(mysqlrouter_up{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\"}, topology)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mysqlrouter_up{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\"}, node_name)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mysqlrouter_up{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\"}, instance)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(mysqlrouter_up{instance=~\"$instance\"}, service_name)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values(mysqlrouter_route_health{instance=~\"$instance\"}, route)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Router Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max by (instance) (mysqlrouter_up{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Scrape Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max by (instance) (mysqlrouter_scrape_error{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Listener All Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max by (instance) (mysqlrouter_listener_all_up{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Listener Check Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max by (instance) (mysqlrouter_listener_check_error{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "time() - max by (instance) (mysqlrouter_start_time_seconds{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max by (instance) (mysqlrouter_scrape_duration_seconds{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Router Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Build Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "mysqlrouter_build_info{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Routes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Route Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "mysqlrouter_route_health{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\", route=~\"$route\"}",
     "legendFormat": "{{instance}} {{route}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "mysqlrouter_route_active_connections{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\", route=~\"$route\"}",
     "legendFormat": "{{instance}} {{route}}"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "mysqlrouter_route_total_connections{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\", route=~\"$route\"}",
     "legendFormat": "{{instance}} {{route}}"
    }
   ]
  },
  {
   "title": "Blocked Hosts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "mysqlrouter_route_blocked_hosts{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\", route=~\"$route\"}",
     "legendFormat": "{{instance}} {{route}}"
    }
   ]
  },
  {
   "title": "Connection Bytes (Active)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "mysqlrouter_route_connection_bytes_from_server{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\", route=~\"$route\"}",
     "legendFormat": "{{instance}} {{route}} from"
    },
    {
     "calculatedInterval": "1m",
     "expr": "mysqlrouter_route_connection_bytes_to_server{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\", route=~\"$route\"}",
     "legendFormat": "{{instance}} {{route}} to"
    }
   ]
  },
  { "title": "Listener Ports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Listener Up",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "mysqlrouter_listener_up{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{route}} {{bind_address}}:{{port}}"
    }
   ]
  },
  { "title": "Destinations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Route Destinations",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "mysqlrouter_route_destination{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\", route=~\"$route\"}"
    }
   ]
  },
  { "title": "Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Metadata Refresh Counters",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "mysqlrouter_metadata_refresh_succeeded{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{metadata}} succeeded"
    },
    {
     "calculatedInterval": "1m",
     "expr": "mysqlrouter_metadata_refresh_failed{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{metadata}} failed"
    }
   ]
  },
  {
   "title": "Metadata Last Refresh Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "mysqlrouter_metadata_last_refresh_info{environment=~\"$environment\", region=~\"$region\", cluster=~\"$cluster\", replication_set=~\"$replication_set\", topology=~\"$topology\", node_name=~\"$node_name\", instance=~\"$instance\"}"
    }
   ]
  }
 ]
}