- name: Check if node_exporter is installed
  ansible.builtin.import_tasks: check_if_node_exporter_installed.yml

- name: Setup and configure node_exporter if not installed
  block:
    - name: Ensure node_exporter package archive is ready(delegate_to dbbot server)
      ansible.builtin.import_tasks: ../../common_utils/tasks/ensure_local_tar_archive_ready.yml
      vars:
        local_tar_archive_label: "node_exporter package {{ node_exporter_package }}"
        local_tar_archive_path: "{{ mysql_packages_dir }}/{{ node_exporter_package }}"
        local_tar_archive_auto_download: "{{ fcs_auto_download_packages | bool }}"
        local_tar_archive_url: "{{ node_exporter_url }}"
        local_tar_archive_timeout: 60
        local_tar_archive_headers:
          User-Agent: "Wget/1.21.1"
        local_tar_archive_validate_certs: false
      when: node_exporter_install_type == 'package'

    - name: Create user and make dir
      ansible.builtin.import_tasks: create_user_and_dir.yml

    - name: Setup node_exporter
      ansible.builtin.import_tasks: setup_node_exporter.yml
      when: node_exporter_install_type == 'package'
    
    - name: Setup pmm node_exporter
      ansible.builtin.import_tasks: setup_node_exporter_not_package.yml
      when: node_exporter_install_type != 'package'

    - name: Manage node_exporter service (create systemd service, enable and start)
      ansible.builtin.import_tasks: manage_service.yml
  when: not node_exporter_stat.stat.exists

- name: Validate node_exporter service is operational
  ansible.builtin.import_tasks: validate_service.yml
