- name: Copy node_exporter package to target server
  ansible.builtin.copy:
    src: "{{ mysql_packages_dir }}/{{ node_exporter_package }}"
    dest: "/tmp/{{ node_exporter_package }}"
    mode: '0644'
  when: not node_exporter_stat.stat.exists

- name: Extract node_exporter binary on target server
  ansible.builtin.unarchive:
    src: "/tmp/{{ node_exporter_package }}"
    dest: "{{ node_exporter_install_dir }}"
    remote_src: true
    extra_opts: ['--strip-components=1']
  when: not node_exporter_stat.stat.exists
  notify:
    - Restart node_exporter
