- name: Check mysqlrouter_exporter port is free
  ansible.builtin.shell: "ss -lnt | awk 'NR>1 && $4 ~ /:{{ mysqlrouter_exporter_port }}$/ {print $4}'"
  register: mysqlrouter_exporter__port_check
  changed_when: false
  failed_when: mysqlrouter_exporter__port_check.stdout != ""
