- name: Write mysqlrouter_exporter config
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ mysqlrouter_exporter_config_file }}"
    owner: "{{ mysqlrouter_exporter_run_user }}"
    group: "{{ mysqlrouter_exporter_run_group }}"
    mode: '0600'
  notify:
    - Restart mysqlrouter_exporter
