- name: Check mysqlrouter_exporter metrics endpoint
  ansible.builtin.uri:
    url: "http://127.0.0.1:{{ mysqlrouter_exporter_port }}{{ mysqlrouter_exporter_metrics_path }}"
    status_code: 200
  register: mysqlrouter_exporter__health
  retries: 5
  delay: 1
  until: mysqlrouter_exporter__health.status == 200
  when: mysqlrouter_exporter_install
