## Configuration for monitoring_prometheus_deployment.yml only ##
[prometheus]
198.51.100.161 ansible_user=root ansible_ssh_pass="'<your_ssh_password>'"

[grafana]
198.51.100.161 ansible_user=root ansible_ssh_pass="'<your_ssh_password>'"

[alertmanager]
198.51.100.161 ansible_user=root ansible_ssh_pass="'<your_ssh_password>'"


[all:vars]
#ansible_python_interpreter=/usr/bin/python3
