- name: Check if master_ip, slave_ip, vip are valid
  ansible.builtin.fail:
    msg: "{{ ansible_play_name }}: `{{ item.key }}` is undefined or not valid"
  loop:
    - { key: 'master_ip', value: "{{ master_ip | default('') }}" }
    - { key: 'slave_ip', value: "{{ slave_ip | default('') }}" }
    - { key: 'vip', value: "{{ vip | default('') }}" }
  when: not (item.value is regex("^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$"))

- name: Check if master_slave.yml 's IP are in inventory/hosts.ini
  ansible.builtin.fail:
    msg: "{{ ansible_play_name }}: master_slave.yml 's IP `{{ item }}` is not in inventory/hosts.ini"
  when: item not in ansible_play_hosts
  loop: "{{ [master_ip] + [slave_ip] }}"

- name: Check if inventory/hosts.ini 's IP are in master_slave.yml
  ansible.builtin.fail:
    msg: "{{ ansible_play_name }}: inventory/hosts.ini's IP `{{ item }}` is not in keepalived_master_slave.yml"
  when: item not in  ([master_ip] + [slave_ip])
  loop: "{{ ansible_play_hosts }}"
