- name: Check if package exists locally (local)
  ansible.builtin.stat:
    path: "{{ packages_dir }}/{{ alertmanager_package }}"
  register: alertmanager_package_file
  delegate_to: 127.0.0.1

- name: Fail if package not found and auto download is disabled (local)
  ansible.builtin.fail:
    msg: "alertmanager package not found and auto download is disabled"
  when: not alertmanager_package_file.stat.exists and not fcs_auto_download
  delegate_to: 127.0.0.1

- name: Download alertmanager binary tarball if not found locally and auto download is enabled (local)
  ansible.builtin.get_url:
    url: "{{ alertmanager_url }}"
    dest: "{{ packages_dir }}/{{ alertmanager_package }}"
    mode: '0644'
    timeout: 30
    headers:
      User-Agent: "Wget/1.21.1"
  when: 
    - not alertmanager_package_file.stat.exists
    - fcs_auto_download | bool
  delegate_to: 127.0.0.1
