- name: Create script to reset Grafana admin password
  ansible.builtin.template:
    src: ../templates/reset_grafana_password.sh.j2
    dest: /tmp/reset_grafana_password.sh
    mode: '0755'

- name: Execute the password reset script
  ansible.builtin.command: /tmp/reset_grafana_password.sh
  register: result
  failed_when: result.rc != 0
