- name: Ensure group -> {{ grafana_run_user_group }} exists
  ansible.builtin.group:
    name: "{{ grafana_run_user_group }}"
    state: present

- name: Create Grafana user -> {{ grafana_run_user }} with no login
  ansible.builtin.user:
    name: "{{ grafana_run_user }}"
    shell: /sbin/nologin
    home: /home/{{ grafana_run_user }}
    group: "{{ grafana_run_user_group }}"
    state: present
