- name: Create Prometheus systemd config file
  ansible.builtin.template:
    src: ../templates/grafana.service.j2
    dest: /etc/systemd/system/grafana.service
    mode: '0644'

- name: Configure Prometheus service to start at boot
  ansible.builtin.systemd:
    name: grafana
    enabled: true
    daemon_reload: true
